### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by kuraydev** [giuseppeg/refined-github-notifications#1]
Hello @giuseppeg,
I love the idea and the design but it does not work on my side :( Simply nothing has changed.

**Comment by giuseppeg** [comment]
Hi @WrathChaos that's odd, do you have access to the new github notifications page?

**Comment by kuraydev** [comment]
@giuseppeg How to check it? I believe that I have the old github notifications page

**Comment by giuseppeg** [comment]
Oh well in that case there is nothing I can do about it unfortunately. In order to get it you should be in the GitHub beta program, and normally they get to decide who's in.

**Comment by kuraydev** [comment]
@giuseppeg Can you tell me where/how to apply the Github beta program? Could not find a proper link.

**Comment by giuseppeg** [comment]
I don't know how if there is a way to apply to the Github beta program. I got added by GitHub without asking for it

**Comment by grahamperrin** [comment]
> be in the GitHub beta program

Please add this criterion at https://chrome.google.com/webstore/detail/refined-github-notificati/apeppglkpocpebbdnocaogepmghkecic so that users are not initially confused. Thank you.
